## 
# Configuration File for Labeler Workflow.
# 
# This files lists all labels and their corresponding globs (paths) to match
#   for the workflow to apply the correct labels for each PR.
#

###############################################################################
 #
 # Copyright (C) 2022-2023 Maxim Integrated Products, Inc. All Rights Reserved.
 # (now owned by Analog Devices, Inc.),
 # Copyright (C) 2023-2024 Analog Devices, Inc. All Rights Reserved. This software
 # is proprietary to Analog Devices, Inc. and its licensors.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
 ##############################################################################

'BLE':
- '**/Examples/**/BLE*/**/*'
- '**/Libraries/BlePhy/**/*'
- '**/Libraries/Cordio/**/*'
- '**/Tools/Bluetooth/**/*'

'documentation':
- '**/Documentation/**/*'

'MAX32520':
- '**/Examples/MAX32520/**/*'
- '**/**/*es17*.*'
- '**/Libraries/Boards/MAX32520/**/*'
- '**/Libraries/CMSIS/Device/Maxim/MAX32520/**/*'
- '**/Libraries/PeriphDrivers/max32520_files.mk'
- '**/Libraries/PeriphDrivers/Include/MAX32520/**/*'

'MAX32570':
- '**/*me13*.*'
- '**/Libraries/Boards/MAX32570/**/*'
- '**/Libraries/CMSIS/Device/Maxim/MAX32570/**/*'
- '**/Libraries/PeriphDrivers/max32570_files.mk'
- '**/Libraries/PeriphDrivers/Include/MAX32570/**/*'

'MAX32572':
- '**/*me55*.*'
- '**/Libraries/Boards/MAX32572/**/*'
- '**/Libraries/CMSIS/Device/Maxim/MAX32572/**/*'
- '**/Libraries/PeriphDrivers/max32572_files.mk'
- '**/Libraries/PeriphDrivers/Include/MAX32572/**/*'

'MAX32650':
- '**/Examples/MAX32650/**/*'
- '**/*me10*.*'
- '**/Libraries/Boards/MAX32650/**/*'
- '**/Libraries/CMSIS/Device/Maxim/MAX32650/**/*'
- '**/Libraries/PeriphDrivers/max32650_files.mk'
- '**/Libraries/PeriphDrivers/Include/MAX32650/**/*'

'MAX32655':
- '**/Examples/MAX32655/**/*'
- '**/*me17*.*'
- '**/Libraries/Boards/MAX32655/**/*'
- '**/Libraries/CMSIS/Device/Maxim/MAX32655/**/*'
- '**/Libraries/PeriphDrivers/max32655_files.mk'
- '**/Libraries/PeriphDrivers/Include/MAX32655/**/*'

'MAX32660':
- '**/Examples/MAX32660/**/*'
- '**/*me11*.*'
- '**/Libraries/Boards/MAX32660/**/*'
- '**/Libraries/CMSIS/Device/Maxim/MAX32660/**/*'
- '**/Libraries/PeriphDrivers/max32660_files.mk'
- '**/Libraries/PeriphDrivers/Include/MAX32660/**/*'

'MAX32662':
- '**/Examples/MAX32662/**/*'
- '**/*me12*.*'
- '**/Libraries/Boards/MAX32662/**/*'
- '**/Libraries/CMSIS/Device/Maxim/MAX32662/**/*'
- '**/Libraries/PeriphDrivers/max32662_files.mk'
- '**/Libraries/PeriphDrivers/Include/MAX32662/**/*'

'MAX32665':
- '**/Examples/MAX32665/**/*'
- '**/*me14*.*'
- '**/Libraries/Boards/MAX32665/**/*'
- '**/Libraries/CMSIS/Device/Maxim/MAX32665/**/*'
- '**/Libraries/PeriphDrivers/max32665_files.mk'
- '**/Libraries/PeriphDrivers/Include/MAX32665/**/*'

'MAX32670':
- '**/Examples/MAX32670/**/*'
- '**/*me15*.*'
- '**/Libraries/Boards/MAX32670/**/*'
- '**/Libraries/CMSIS/Device/Maxim/MAX32670/**/*'
- '**/Libraries/PeriphDrivers/max32670_files.mk'
- '**/Libraries/PeriphDrivers/Include/MAX32670/**/*'

'MAX32672':
- '**/Examples/MAX32672/**/*'
- '**/*me21*.*'
- '**/Libraries/Boards/MAX32672/**/*'
- '**/Libraries/CMSIS/Device/Maxim/MAX32672/**/*'
- '**/Libraries/PeriphDrivers/max32672_files.mk'
- '**/Libraries/PeriphDrivers/Include/MAX32672/**/*'

'MAX32675':
- '**/Examples/MAX32675/**/*'
- '**/*me16*.*'
- '**/Libraries/Boards/MAX32675/**/*'
- '**/Libraries/CMSIS/Device/Maxim/MAX32675/**/*'
- '**/Libraries/PeriphDrivers/max32675_files.mk'
- '**/Libraries/PeriphDrivers/Include/MAX32675/**/*'
- '**/*aes_me15*.*'
- '**/*afe*'
- '**/*crc_me15*.*'
- '**/*dma*me15*.*'
- '**/*gpio*me15*.svd'
- '**/*flc*me15*.*'
- '**/*i2c*me15*.*'
- '**/*i2s*me15*.*'
- '**/*icc*me15*.*'
- '**/*lp*me15*.*'
- '**/*pwrseq*me15*.*'
- '**/*lpgcr_me17*.*'
- '**/*mcr_me15*.svd'
- '**/*rtc*me15*.svd'
- '**/*sir_me15*.svd'
- '**/*spi*me15*.*'
- '**/*sys_me15*.c'
- '**/*tmr*me15*.svd'
- '**/*trimsir_me15*.*'
- '**/*wdt*me15*.*'

'MAX32680':
- '**/Examples/MAX32680/**/*'
- '**/*me20*.*'
- '**/Libraries/Boards/MAX32680/**/*'
- '**/Libraries/CMSIS/Device/Maxim/MAX32680/**/*'
- '**/Libraries/PeriphDrivers/max32680_files.mk'
- '**/Libraries/PeriphDrivers/Include/MAX32680/**/*'
- '**/*adc*me17*.*'
- '**/*aes_me17*.*'
- '**/*afe*'
- '**/*crc_me17*.*'
- '**/*dma*me17*.*'
- '**/*gpio*me17*.*'
- '**/*flc*me17*.*'
- '**/*i2c*me17*.*'
- '**/*icc*me17*.*'
- '**/*lp*me17*.*'
- '**/*pwrseq_me17*.*'
- '**/*lpgcr_me17*.*'
- '**/*owm*me17*.*'
- '**/*rtc*me17*.*'
- '**/*sema*me17*.*'
- '**/*simo*me17*.*'
- '**/*spi*me17*.*'
- '**/*sys_me17*.c'
- '**/*tmr_me17*.c'
- '**/*sir_me17*.*'
- '**/*trimsir_me17*.*'
- '**/*uart*me17*.*'
- '**/*wut*me17*.*'

'MAX32690':
- '**/Examples/MAX32690/**/*'
- '**/*me18*.*'
- '**/Libraries/Boards/MAX32690/**/*'
- '**/Libraries/CMSIS/Device/Maxim/MAX32690/**/*'
- '**/Libraries/PeriphDrivers/max32690_files.mk'
- '**/Libraries/PeriphDrivers/Include/MAX32690/**/*'

'MAX78000':
- '**/Examples/MAX78000/**/*'
- '**/*ai85*.*'
- '**/Libraries/Boards/MAX78000/**/*'
- '**/Libraries/CMSIS/Device/Maxim/MAX78000/**/*'
- '**/Libraries/PeriphDrivers/max78000_files.mk'
- '**/Libraries/PeriphDrivers/Include/MAX78000/**/*'
- '**/*adc*me17*.*'
- '**/*aes_me17*.*'
- '**/*crc_me17*.*'
- '**/*dma_me17*.*'
- '**/*flc*me17*.*'
- '**/*i2c*me17*.*'
- '**/*icc*me17*.*'
- '**/*owm*me17*.*'
- '**/*rtc*me17*.*'
- '**/*sema*me17*.*'
- '**/*spi*me17*.*'
- '**/*trimsir*me17*.*'
- '**/*uart*me17*.svd'
- '**/*wdt_me17*.*'
- '**/*wut*me17*.svd'

'MAX78002':
- '**/Examples/MAX78002/**/*'
- '**/*ai87*.*'
- '**/Libraries/Boards/MAX78002/**/*'
- '**/Libraries/CMSIS/Device/Maxim/MAX78002/**/*'
- '**/Libraries/PeriphDrivers/max78002_files.mk'
- '**/Libraries/PeriphDrivers/Include/MAX78002/**/*'

'Register Change':
- '**/*_regs.h'
- '**/*.svd'

'Tools':
- '**/Tools/**/*'

'Workflow':
- '**/.github/workflows/**/*'
- '**/.github/**/*'
